{application,nitrogen,
             [{description,"My Nitrogen Web Project"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{nitrogen_app,[]}},
              {env,[]},
              {modules,[index,login,main,nitrogen_app,nitrogen_mochiweb,
                        nitrogen_sup,password,pizza,register,twitter,
                        written_comparison]}]}.
